[ci] Remove bats vestigial files, fix repipe

diff --git a/ci/scripts/build-test-jobs b/ci/scripts/build-test-jobs
--- a/ci/scripts/build-test-jobs
+++ b/ci/scripts/build-test-jobs
@@ -51,15 +51,15 @@ env_prefix="ci-$iaas-"
 read -d '' -r -a envs < <(cd "$base_dir/envs" && echo "$env_prefix"*.yml) || true
 echo >&2 $'\n'"${#envs[@]} environments found: ${envs[*]}"$'\n'
 for env in "${envs[@]+"${envs[@]}"}" ; do
-	env_name="$(sed -e "s/^$env_prefix//" -e 's/\.yml$//' <<<"$env")"
+  env_name="$(sed -e "s/^$env_prefix//" -e 's/\.yml$//' <<<"$env")"
   env_hierarchy=()
   subpath=''
-  for fragment in ${env//-/ -}; do
+  for fragment in ${env_name//-/ -}; do
     subpath=$subpath$fragment
-    [[ -f "$base_dir/envs/$subpath.yml" ]] || continue
-    env_hierarchy+=( "$base_dir/envs/$subpath.yml" )
+    [[ -f "$base_dir/envs/$env_prefix$subpath.yml" ]] || continue
+    env_hierarchy+=( "$base_dir/envs/$env_prefix$subpath.yml" )
   done
-  env_ci="$(spruce merge --skip-eval "${env_hierarchy[@]}" | spruce json | jq -r '.kit.ci//{}')"
+  env_ci="$(spruce merge "${env_hierarchy[@]}" | spruce json | jq -r '.kit.ci//{}')"
 
   [[ $(_lookup "$env_ci" '.skip//false') == "true" ]] && continue
 
@@ -85,8 +85,19 @@ for env in "${envs[@]+"${envs[@]}"}" ; do
   type="$(_lookup "$env_ci" '.type//"deploy"')"
   if [[ $type == 'custom' ]] ; then
     src="$(_lookup "$env_ci" '.path//"pipeline/custom-jobs/'"$job"'.yml"')"
-    cp "$base_dir/$src" "$file"
     echo >&2 "Building custom test job for env $env_name using $src"
+    if [[ ! -f "$base_dir/$src" ]] ; then
+      echo >&2 "Custom job file not found: $src"
+      exit 1
+    fi
+    cp "$base_dir/$src" "$file"
+    while read -r resource; do
+      if [[ ! -f "$base_dir/pipeline/custom-resources/${resource}.yml" ]] ; then
+        echo >&2 "Custom resource file for $job not found: $resource"
+        exit 1
+      fi
+      cp "$base_dir/pipeline/custom-resources/${resource}.yml" "$base_dir/pipeline/tests/"
+    done < <(_lookup "$env_ci" '.resources//[] | .[]')
     continue
   fi
 
